### ISSUE TITLE
Quantity in the Cart Edit Popup is not connected with the quantity on the cart page

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#223]
### Description

While working on a ticket, I noticed that there are some problems with the cart edit popup.

If you click on the cart edit popup, then open the configurations popup, make some selections, and insert a certain quantity, it will not be reflected on the cart page.

### Step-by-step reproduction instructions

1. Enable the fields popup (in Products > Select a Product > PPOM Fields)
2. Enable cart edit (in WooCommerce > Settings > PPOM Settings > Addons > Cart Edit)
3. Enable popup cart edit
4. Go to a PPOM product
5. Make some configurations in the popup
6. Go to the cart page
7. Click on Fields Popup
8. Open the configurations popup
9. Insert a quantity there and click Update
10. The cart page will be refreshed, but the quantity will not be different

### Screenshots, screen recording, code snippet or Help Scout ticket

I know it might be hard to understand, but you can see the behavior in this video:
https://vertis.d.pr/v/eODZqn

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina

I have fixed this issue via this PR Codeinwp/ppom-pro#290

Thanks

**Comment by irinelenache** [comment]
@kushh23 Can you try to test this fix as part of the QA knowledge-sharing initiative?

**Comment by kushh23** [comment]
@irinelenache , sure. Let me try it, and I will follow up with the results.

**Comment by kushh23** [comment]
@irinelenache @girishpanchal30  I have tested this and found that with this fix, the value input field is not working correctly, see here - https://vertis.d.pr/v/5gAbRz

When I try to manually enter some value or increase it by the up, down buttons, they doesn't work.

**Comment by kushh23** [comment]
It Can be checked here - https://preferable-newt-ac0b13.vertisite.cloud/

**Comment by girishpanchal30** [comment]
Hey @kushh23

It seems working from my end.

Above provided  instance is not working so can you please provide new one.

Thanks

**Comment by kushh23** [comment]
Hi @girishpanchal30 

Can you please try again, the site was expired but I have restored and reserved it so it won't expire again.

Let me know how it goes, thank you!

**Comment by girishpanchal30** [comment]
Hey @kushh23

Can you please share the wp-admin credentials?

Thanks

**Comment by girishpanchal30** [comment]
Hey @kushh23

I have fixed this issue with this PR Codeinwp/ppom-pro#290

I have removed default qty field when bulk qty field is used, because we do not need default qty field while using bulk qty field.

Thanks

**Comment by kushh23** [comment]
Hi @girishpanchal30,

I apologize for the delay. I tested the product and still encountered the same issue I mentioned before. However, I noticed a small detail this time. If you add the ### conditional image input field to the product and try the field popup option in the cart, the value input field doesn't work correctly if no option is selected. It only works correctly when an image option is selected. You can see a screencast video of this issue at https://vertis.d.pr/v/2PoeHS.

I also checked the chained input field, and the issue is the same. Even when I select an option, the field doesn't work correctly. You can see a video of this at https://vertis.d.pr/v/9hhvH7.

Here are the instance details:

```
https://charismatic-plover-a1814d.vertisite.cloud/
kush@themeisel.com
K$#c9E0PTK&9XcSw!O$6(9cD
```

**Comment by girishpanchal30** [comment]
@kushh23 I've checked with the development branch and I can't replicate this issue anymore.

> https://charismatic-plover-a1814d.vertisite.cloud/
kush@themeisel.com
K$#c9E0PTK&9XcSw!O$6(9cD

It seems the test instance is expired, Could you please recheck it? and let me know if you fetch the issue.

Thanks

**Comment by stefan-cotitosu** [comment]
@AndreeaCristinaRadacina, please help Girish here with the testing as Kush is not available today.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 @stefan-cotitosu I tested the product but couldn't encounter the issues Kush mentioned.

From what I see, the behavior I shared is no longer replicable; it has already been resolved.

If Kush still encounters those issues, maybe he can open a new issue when he comes back.

What I have observed is that the field popup doesn't work when using the conditional images - it is not clickable. You can see the problem here - https://programstatement.s2-tastewp.com/product/exotic-parrot/:

1. Use the popup and select an image.
2. Add to cart.
3. Click on the Field Popup button in the cart and try to click on the Popup button.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 thanks for checking!

I uploaded the zip, but the issue persists. I created a user for you:

1. 3SX7@1UbcAtZqPNkVX$rh6##
2. Girish
3. https://programstatement.s2-tastewp.com/wp-admin

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina It seems cache issue in this instance, I can't see my changes in js/ppom-simple-popup.js - https://github.com/Codeinwp/woocommerce-product-addon/pull/326/commits/d18c4420c8160d664e0f7b5e871f694e6db4b975

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 I cleared the browser cache and used LiteSpeed for WP cache; I can see the change in the code:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/64cc4767-1e0a-44f3-b877-32e87790f1ba">

But unfortunately, the issue persists:
https://programstatement.s2-tastewp.com/d09c8-pet-shop-cart/#ppom_cart_popup_show_bde2567438c6328931aff15fc921334b

Let me know what you think!

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina JS changes do not reflect on the browser.
Ref: https://tinyurl.com/29vj9oy7

Can you please check with a fresh instance?

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 Great, I tested on a fresh instance, and everything is fine - https://elegantpencil.s4-tastewp.com/product/black-hat/.

Thank you for taking care!
